### ISSUE TITLE
KIM Integration - redesign configuration after migration is done

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/kyma-environment-broker#1241]
When we use KIM only, provisioner is no longer used, we need to simplify and unify configuration.

To many steps we pass separately `input.Config` and `broker.KimConfig` objects.

Phase 1 AC: 12.2024
- [x] 1) go further with how to adjust our configurations, start with https://github.com/kyma-project/kyma-environment-broker/issues/1241#issuecomment-2401679977. Prepare final yaml config for KIM (Assuming provisioner is already removed) that we will use in the management-plane-config. [Comment](https://github.com/kyma-project/kyma-environment-broker/issues/1241#issuecomment-2544809244)

Phase 2 AC: 01.2025
- [x] 1) we pass one configuration object to all steps that need it
- [x] 2) there are no longer `provisioner` related settings - waiting till changes deployed on PROD
- [x] 3) KIM migration related settings are removed
- [x] 4) some previously used settings become KIM related and possible should be moved to a new section

**Comment by jaroslaw-pieszka** [comment]
Following configuration values should be migrated to `kim` section (are used to create Runtime CRs`:

- `Provisioner.KubernetesVersion`
- `Provisioner.DefaultGardenerShootPurpose`
- `Provisioner.MachineImage`
- `Provisioner.MachineImageVersion`
- `Provisioner.DefaultTrialProvider`
- `Provisioner.MultiZoneCluster`
- `Provisioner.ControlPlaneFailureTolerance`

We could consider moving:
- `Broker.UseSmallerMachineTypes` to `kim` section

Following values should be moved to other place (possible section with timeouts - there are more timeouts settings scattered):
- `Provisioner.ProvisioningTimeout`
- `Provisioner.DeprovisioningTimeout`
- `Provisioner.RuntimeResourceStepTimeout`
- `Provisioner.ClusterUpdateStepTimeout`

Following values should be removed (double check before actual removal):
- `Provisioner.URL`
- `Provisioner.TrialNodesNumber`
- `Provisioner.AutoUpdateKubernetesVersion`
- `Provisioner.AutoUpdateMachineImageVersion`
- `Provisioner.EnableShootAndSeedSameRegion`

Removal is blocked until `provisioner` is decommissioned and only KIM is driving/controlling the process.

**Comment by jaroslaw-pieszka** [comment]
This is blocked by #1187 and ...

**Comment by KsaweryZietara** [comment]
`management-plane-config`:
```
gardener:
  defaultShootPurpose:
  defaultTrialProvider:
  kubernetesVersion:
  machineImage:
  machineImageVersion:
  multiZoneCluster:
  controlPlaneFailureTolerance: 
timeouts:
  provisioning:
  deprovisioning:
  gardenerClusterStep:
  runtimeResourceStep:
  clusterUpdateStep:
  checkRuntimeResourceDeletionStep:
  kymaResourceDeletion:
```
