### ISSUE TITLE
Correct Labels to lowerCamelCase  in HAP Documentation

### ISSUE THREAD

**Issue by ralikio** [kyma-project/kyma-environment-broker#1623]
On the environment we have secrets bindings defined with the following structure:

```
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    cloudprofile.garden.sapcloud.io/name: gcp
    hyperscalerType: gcp
    provider.extensions.gardener.cloud/gcp: "true"
    tenantName: ...
  ...
```

but in the documentation labels are provided as follows:

https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/03-10-hyperscaler-account-pool.md?plain=1#L40-L47
