### ISSUE TITLE
Store Kyma customer account data in dedicated CRD

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma-environment-broker#1786]
Created on 2025-02-28 by Tobia Schuhmacher (@tobiscr)

## Decision log

| Name | Description |
|-----------------------|------------------------------------------------------------------------------------|
| Title | Store account data in KCP in CRD instead using labels on Runtime-CR or Kyma-CR|
| Due date | 2012-03-30 |
| Status |Proposed|
| Decision type | Binary |
| Affected decisions |None|

## Context

Several KCP component require access to customer acocunt data (e.g. monitoring from SRE, Cloud MAnager (?)). Single point of truth in Kyma for customer account data is KEB. It makes them consumable for other components by adding them as labels to `Runtime` and `Kyma` CRs.

This approach as several pros / cons:

|Pro + / Con -|Description|
|--|--|
|+|Can be use for querying CRs by using account data as query constraints|
|-|Labels can not be treated as technical contract as they can be missing, modified or having a wrong data type/format|
|-|Customer data are stored redundantly over multiple CRs. They have to be maintained by KEB and can run out of sync. Adding more CRs increases redundancy|
|-|Exposing further account attributes increase the amount of applied labels on each Runtime / Kyma CR|

We want to change this approach by:

1. Adding another Account CRD to KCP which stores a customer GA and subaccounts / Kyma runtimes
2. Reduce the exposed labels on RuntimeCRs to the required labels (add only these labels which are really used in queries)

Example of an account CRD can be:

```
apiVersion: accountpool.kyma-project.io/v1
kind: Account
metadata:
  labels:
    kyma-project.io/global-account-id: 6c6d9dc7-b2f8-4d8c-981b-95f9b80656cf
    kyma-project.io/region: westeurope
    kyma-project.io/subaccount-id: 8f65116b-6658-4912-ac1e-eb11450f2d6c
  namespace: kcp-system
spec:
  global-account-id: 123-123-123-123
  subaccounts:
  - abc-abc-abc-abc:
        region: westeurope
        runtimes:
        -  runtime-id: e201b7-c9a6-4c2c-88d9-89877914
           shoot-name: c-ede314
           region: us-west-1
           btp-region: cf-us02
           plan-name: azure
           plan-id: e563-e5ec-4731-b9b1-53b42d8
           kyma-id: e563-e5-898d-234-53b42d8
        -  runtime-id: 92834-c9a6-xxde3-88d9-74732
           shoot-name: c-ckyue2d
           region: us-east-1
           btp-region: cf-us05
           plan-name: azure
           plan-id: abcd2-e5ec-3984-b9b1-2993b33
           kyma-id: 13b2-a6-8313-123123-ba38
           
```
