### ISSUE TITLE
KEB allows configuration for available hyperscalers/regions per plan

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1902]
**AC**:
- [x] 0) Design new configuration and present to the team. When approved release document like we did for HAP Rules Specification.
- [x] 1) move our hardcoded regions/zones in KEB to configuration per plan
  - keep allowing to set the given order of the regions (https://github.tools.sap/kyma/management-plane-config/pull/6478) merged
  - Docs: https://github.com/kyma-project/kyma-environment-broker/pull/2045
- [x] 2) Remove from dev, stage, prod not used (by KEB) sapConvergedCloudPlanRegionMappings settings: **waiting for a proper version on PROD**
- [x] 3) move our hardcoded machineTypes in KEB to configuration per plan (main and additionalWorkers separately)
  - keep allowing to set the given order of the machineTypes  https://github.tools.sap/kyma/management-plane-config/pull/6530
- [ ] 4) ~For Kyma workerPool configuration with zones requires at lest 3. To support only HA mode for this pool.~
- [x] 5) Introduce Plan centric configuration, decide what goes into plan config, what stays away of the plan, see info section. NOTE: we can do that now or never, cause when first Restricted Market will be released, our configurations must be backward compatible.
- [x]  5) Configure  us50-canary KEB config accordingly: https://github.tools.sap/kyma/landscape-us50-canary/blob/main/kcp/values/keb-sap.yaml

**Info**

KEB can read configuration for plans:
https://github.com/kyma-project/kyma-environment-broker/blob/8afc9a6192609ae1641eaf7e211a8d02aefe6fdd/cmd/broker/main.go#L266

We can extract hardcoded configs (regions, machines) from KEB to a ConfigMap. To separate configurations we can use kustomize to build the final result.

Example:
```
runtimeConfiguration: |-
  default: |- # < ----- PLAN
    kyma-template: |- # < ----- ONE OF POSSIBLE MANY CONFIG FIELDS
      apiVersion: operator.kyma-project.io/v1beta2
      kind: Kyma
      metadata:
        labels:
          "operator.kyma-project.io/managed-by": "lifecycle-manager"
        name: tbd
        namespace: kcp-system
      spec:
        channel: fast
        modules: []
    additional-components: []
  
  gcp: |-
    hap:
      - gcp -> S
  
  aws: |-
    hap:
      - aws

```
