### ISSUE TITLE
Enable g6 and g4 machine types for aws plan in the two regions from subset of all zones

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1924]
**Description**

Working on adding G4 machine types for aws: [ticket](https://github.com/kyma-project/kyma-environment-broker/issues/1854#issuecomment-2771879005), we figured out that two region has more than 3 zones we support:
- 5 zones: "us-east-1": "abcdf" | g6 is not suported in f
- 4 zones: "us-west-2": "abcd" | g4 not supported in d

We created ticket to infrastructure manager to allow KEB to use any 3 ouf of all zones for given worker pools: [KIM ticket](https://github.com/kyma-project/infrastructure-manager/issues/804)

**AC**
- [x] 1) [KIM ticket](https://github.com/kyma-project/infrastructure-manager/issues/804) is closed and deployed to all environments
- [x] 2) Extend out current region <-> machineType mapping to include zones too, see details with proposal
https://github.com/kyma-project/kyma-environment-broker/pull/1998 
https://github.com/kyma-project/kyma-environment-broker/pull/2008
https://github.com/kyma-project/kyma-environment-broker/pull/2026
- [x] 3) Support g6 in "us-east-1" and support g4 in "us-west-2" 
https://github.tools.sap/kyma/management-plane-config/pull/6470
  - [x] 3.1) Regions where zones are not provided in the mapping, uses current mechanism
  - [x] 3.2) dev [#6449](https://github.tools.sap/kyma/management-plane-config/pull/6449), [#6498](https://github.tools.sap/kyma/management-plane-config/pull/6498)
  - [x] 3.3) stage [#6455](https://github.tools.sap/kyma/management-plane-config/pull/6455), [#6501](https://github.tools.sap/kyma/management-plane-config/pull/6501)
  - [x] 3.4) prod [#6472](https://github.tools.sap/kyma/management-plane-config/pull/6472), [#6515](https://github.tools.sap/kyma/management-plane-config/pull/6515)
- [x] 4) Support regions with only 1 or 2 zones. User can use given machine type in such a region only if HA is set to FALSE. If user marked HA true then fail with message like: "This region has no 3 zones. If you want to use this machine type you need to set HA to false".
- [x] 5) when HA is false, KEB always randomly selects one zone only. Regardless if region has 2,3 or 4 zones. Must select one from the configured ones. E.g.       - us-eastwest13 has only a & b. That means it should select one, a or b.
- [x] ~6) When workerPool is added we always pick random zones. When machineType is changed, again random zones from available ones. **Check if changing one zone a to zone b is possible**~
  - [x] 6.1) what we can do on KEB side:
    - [x] 6.1.1) not allow to change machineType for existing workerPools in schema, DECISION MADE, THIS IS A WAY TO GO, or: https://github.com/kyma-project/kyma-environment-broker/pull/2003
    - [ ] ~6.1.2) allow, and if zones doesnt fit fail with validation message with explanation (e.g. you need to delete and create worker pool for such a change)~
- [x] 7) Remove `zoneMapping` and `disableMachineTypeUpdate` feature flags 
https://github.com/kyma-project/kyma-environment-broker/pull/2034
    - [x] 7.1) Remove feature flags from management-plane-config (KEB 1.19.3 on all environments)

**Proposal**

```
regionsSupportingMachine: |-
...
    g6:
      - us-east-1
        - abcd
      - us-west-2
    g4dn:
      - eu-central-1
      - eu-west-2
      - us-east-1
      - ap-south-1
      - us-west-2
        - abc
    g2-standard:
      - asia-south1
      - us-west1
      - us-central1
      - europe-west4
      - europe-west3
        - ab
...
```

**INFO**
About 6.1.1) document that machineType change for additionalWorkers requires creation of the new worker, migrate workloads and delete old worker

**Blocked**
- https://github.com/kyma-project/infrastructure-manager/issues/887

**Comment by KsaweryZietara** [comment]
I’d like to suggest a slightly adjusted format for the `regionsSupportingMachine` structure to make zone mappings more explicit and easier to parse programmatically:
```
regionsSupportingMachine: |-
    g6:
      us-east-1: [a, b, c, d]
      us-west-2:
    g4dn:
      eu-central-1:
      eu-west-2:
      us-east-1:
      ap-south-1:
      us-west-2: [a, b, c]
    g2-standard:
      asia-south1:
      us-west1:
      us-central1:
      europe-west4:
      europe-west3: [a, b]
```
