### ISSUE TITLE
Refactor KEB after Reconciler removal

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#536]
**Description**
This ticket is an outcome of the [TASK](https://github.com/kyma-project/control-plane/issues/2498).

**AC**
- [x] 1) Remove (or modify) unnecessary steps (listed in the previous comment)
  - [x] 1.1) LM manager does not get any overrides, additional components and Kyma Version. 
  - [x] 1.2) make keb-config.yaml global per environment (right now it is per KymaVersion [See](https://github.tools.sap/kyma/management-plane-config/blob/main/resources/runtimes/2.16/dev/keb-config.yaml)) 
  https://github.com/kyma-project/kyma-environment-broker/pull/779
  - [x] 1.3) follow [Comment](https://github.com/kyma-project/control-plane/issues/2498#issuecomment-1598169013)
- [x] 2) Cleanup RuntimeInput, InputBuilderFactory https://github.com/kyma-project/kyma-environment-broker/pull/786
- [x] 3) Remove unused packages, make sure reconciler dependency is not used 
https://github.com/kyma-project/kyma-environment-broker/pull/789, https://github.com/kyma-project/kyma-environment-broker/pull/802
- [x] 4) Remove `kcp rc` commands from skr-e2e-tests @MarekMichali https://github.com/kyma-project/kyma-environment-broker/pull/782
- [x] 5) Release tp DEV, provide a cluster for all teams to tests
- [x] 6) Release to STAGE, provide a cluster for all teams to tests
- [x] 7) Release to PROD, provide a cluster for all teams to tests
- [ ] 8) Update docs https://github.com/kyma-project/kyma-environment-broker/pull/824
   - [x] [docs/user/01-10-architecture.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/01-10-architecture.md) 
   - [x] [docs/user/03-10-service-description.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/03-10-service-description.md) - which parameters to remove? (SME @KsaweryZietara )
   - [ ] [docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md) - needs thorough revision (SME @piotrmiskiewicz )
   - [x] [configuring-keb.md](https://github.tools.sap/kyma/documentation/blob/main/kyma-internal/how-to-guides/configuring-keb.md) (SME @piotrmiskiewicz )
   - [x] [provisioning-skr-via-KEB.md](https://github.tools.sap/kyma/documentation/blob/main/kyma-internal/how-to-guides/provisioning-skr-via-KEB.md) - check the parameters (SME @KsaweryZietara ); link to the parameters topic in HP
   - [x] [provisioning-skr.md](https://github.tools.sap/kyma/documentation/blob/main/kyma-internal/how-to-guides/provisioning-skr.md) - remove the part about versions (SME @piotrmiskiewicz  @KsaweryZietara )
   - [x] [setting-kyma-version.md](https://github.tools.sap/kyma/documentation/blob/main/kyma-internal/how-to-guides/setting-kyma-version.md) - the part about versions must be removed (along with the code)
   - [x] [diagnostics.md](https://github.tools.sap/kyma/documentation/blob/main/kyma-internal/support/on-call-guides/kcp/kyma-environment-broker/diagnostics.md) - must check what you can see in KCP (version)
- [x] 9) Check if kyma upgrade capabilities in KEB are still needed 
https://github.com/kyma-project/kyma-environment-broker/issues/828
- [x] 10) https://github.com/kyma-project/kyma-environment-broker/pull/861

**Note**
- first remove renconciler steps (use feature flag for every environment) https://github.com/kyma-project/kyma-environment-broker/pull/751, then
- cleanup KEB code https://github.com/kyma-project/kyma-environment-broker/pull/775

**Comment by piotrmiskiewicz** [comment]
Ideas, how to avoid problems with ArgoCD:
1. Change `kind:` to `kind_ArgoSucks:`, then implement a `config/reader_for_argo` which do a string.replace operation on the input. Example
```
runtimeConfiguration: |-
    own_cluster:
      kyma-template: |-
        apiVersion: operator.kyma-project.io/v1beta2
        kind_ArgoSucks: Kyma
        metadata:
          labels:
            "operator.kyma-project.io/managed-by": "lifecycle-manager"
        name: tbd
        namespace: kcp-system
      spec:
        channel: fast
        modules: []
      additional-components: []
    default:
      kyma-template: |-
        apiVersion: operator.kyma-project.io/v1beta2
        kind_ArgoSucks: Kyma
        metadata:
          labels:
            "operator.kyma-project.io/managed-by": "lifecycle-manager"
        name: tbd
        namespace: kcp-system
      spec:
        channel: fast
        modules:
          - name: api-gateway
          - name: istio
          - name: btp-operator
      additional-components: []
```
Disadvantage: Ugly config
2.  Configure `kind: Kyma` outside of the main config:
```
kymaTemplateKind: Kyma
runtimeConfiguration: |-
    own_cluster:
      kyma-template: |-
        apiVersion: operator.kyma-project.io/v1beta2
        metadata:
          labels:
            "operator.kyma-project.io/managed-by": "lifecycle-manager"
        name: tbd
        namespace: kcp-system
      spec:
        channel: fast
        modules: []
      additional-components: []
    default:
      kyma-template: |-
        apiVersion: operator.kyma-project.io/v1beta2
        metadata:
          labels:
            "operator.kyma-project.io/managed-by": "lifecycle-manager"
        name: tbd
        namespace: kcp-system
      spec:
        channel: fast
        modules:
          - name: api-gateway
          - name: istio
          - name: btp-operator
      additional-components: []
```
