### ISSUE TITLE
Support two zones for ap-au-1  CCEE region

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#868]
**AC**
- [x] 1) use both available zones for ap-au-1. Every region has different number of zones.
```
- name: ap-au-1
    zones:
    - name: ap-au-1a
    - name: ap-au-1b
```
