### ISSUE TITLE
[CCEE/ 8 regions] rollout of na-us-1 / eu-de-2 / na-us-2 / ap-jp-1 / ap-ae-1

### ISSUE THREAD

**Issue by KsaweryZietara** [kyma-project/kyma-environment-broker#954]
Main Story: https://github.tools.sap/kyma/backlog/issues/5392
5 last regions: https://github.tools.sap/kyma/backlog/issues/5701

**AC**
- [x] 1) Plan is to expose all of then in the Canary environment, and in the Prod just na-us-1 for now, details in the 5701 ticket 
[#5477](https://github.tools.sap/kyma/management-plane-config/pull/5477), [#5522](https://github.tools.sap/kyma/management-plane-config/pull/5522), [#5525](https://github.tools.sap/kyma/management-plane-config/pull/5525), [#5529](https://github.tools.sap/kyma/management-plane-config/pull/5529), [#5558](https://github.tools.sap/kyma/management-plane-config/pull/5558), [#5586](https://github.tools.sap/kyma/management-plane-config/pull/5586), [#5588](https://github.tools.sap/kyma/management-plane-config/pull/5588), [5663](https://github.tools.sap/kyma/management-plane-config/pull/5663), [5702](https://github.tools.sap/kyma/management-plane-config/pull/5702), [5839](https://github.tools.sap/kyma/management-plane-config/pull/5839)
- [x] 2) For new regions check all allowed zones we need to pass to provisioner (Check in Gardener live for proper zones names)
https://github.com/kyma-project/kyma-environment-broker/pull/957
- [x] 3) Prepare RN and docs with internal section ([Regions for the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/regions-for-kyma-environment?locale=en-US&state=DRAFT&version=Internal) and [Provisioning and Updating Parameters in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/provisioning-and-update-parameters-in-kyma-environment?locale=en-US&state=DRAFT&version=Internal#loioe2e13bfaa2f54a4fb179f0f1f840353a__section_Region)) (Iwona)

**Comment by KsaweryZietara** [comment]
## Allowed zones for new regions

```
    - name: na-us-1
      zones:
      - name: na-us-1a
      - name: na-us-1b
      - name: na-us-1d
    - name: eu-de-2
      zones:
      - name: eu-de-2a
      - name: eu-de-2b
    - name: na-us-2
      zones:
      - name: na-us-2a
      - name: na-us-2b
    - name: ap-jp-1
      zones:
      - name: ap-jp-1a
    - name: ap-ae-1
      zones:
      - name: ap-ae-1a
      - name: ap-ae-1b
```
